### ISSUE TITLE
Branching model is not important for a one-person project

### ISSUE THREAD

**Issue by yungyuc** [minchuncho/sewup#1]
I noticed that you are making a distinct branch for adding code.  It's a good practice.  But for a one-person project, you do not have to do it.

It's more important to check in code faster and have it tested.

**Comment by minchuncho** [comment]
In case I take it the wrong way, did you mean the branch `phase-one`?

**Comment by yungyuc** [comment]
Correct.

I open the issue only to make the comment.  Feel free to close it since you have read it.
